import { Project, Task, Sprint } from '@/types';

export const initialProjects: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'TaskFlow Pro',
    description: 'Современная система управления задачами для Product Managers',
    key: 'TFP',
    color: '#3B82F6',
  },
  {
    name: 'Мобильное приложение',
    description: 'Разработка мобильного приложения для iOS и Android',
    key: 'MOB',
    color: '#10B981',
  },
];

export const initialSprints: Omit<Sprint, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Sprint 01.08.25',
    goal: 'Поставить авторизацию со всеми необходимыми функциональностями',
    projectId: 'project-1', // Будет заменено на реальный ID
    startDate: new Date('2025-07-30'),
    endDate: new Date('2025-08-13'),
    capacity: 40,
    status: 'active',
  },
  {
    name: 'Sprint 02.08.25',
    goal: 'Реализовать основные экраны приложения',
    projectId: 'project-1', // Будет заменено на реальный ID
    startDate: new Date('2025-08-14'),
    endDate: new Date('2025-08-27'),
    capacity: 35,
    status: 'planned',
  },
  {
    name: 'Sprint 01.07.25',
    goal: 'Подготовка архитектуры проекта',
    projectId: 'project-1', // Будет заменено на реальный ID
    startDate: new Date('2025-07-01'),
    endDate: new Date('2025-07-14'),
    capacity: 30,
    status: 'completed',
  },
];

export const initialTasks: Omit<Task, 'id' | 'createdAt' | 'updatedAt' | 'watchers' | 'attachments' | 'linkedTasks'>[] = [
  // Задачи для активного спринта
  {
    title: 'Настроить аутентификацию через JWT',
    description: 'Реализовать систему аутентификации с использованием JWT токенов',
    type: 'story',
    status: 'in-progress',
    priority: 'high',
    storyPoints: 8,
    position: 1,
    projectId: 'project-1',
    assigneeId: 'user-1',
    reporterId: 'user-1',
    sprintId: 'sprint-1', // Будет заменено на реальный ID
    labels: ['auth', 'backend'],
    dueDate: new Date('2025-08-10'),
    estimatedHours: 16,
    loggedHours: 8,
  },
  {
    title: 'Создать компонент формы входа',
    description: 'Разработать UI компонент для страницы входа в систему',
    type: 'story',
    status: 'todo',
    priority: 'medium',
    storyPoints: 5,
    position: 2,
    projectId: 'project-1',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    sprintId: 'sprint-1',
    labels: ['ui', 'frontend'],
    dueDate: new Date('2025-08-12'),
    estimatedHours: 12,
    loggedHours: 0,
  },
  {
    title: 'Добавить валидацию форм',
    description: 'Реализовать клиентскую и серверную валидацию для форм регистрации и входа',
    type: 'story',
    status: 'in-review',
    priority: 'high',
    storyPoints: 6,
    position: 3,
    projectId: 'project-1',
    assigneeId: 'user-3',
    reporterId: 'user-1',
    sprintId: 'sprint-1',
    labels: ['validation', 'security'],
    dueDate: new Date('2025-08-13'),
    estimatedHours: 10,
    loggedHours: 10,
  },
  {
    title: 'Исправить баг с редиректом после логина',
    description: 'После успешного входа пользователь не перенаправляется на главную страницу',
    type: 'bug',
    status: 'done',
    priority: 'urgent',
    storyPoints: 2,
    position: 4,
    projectId: 'project-1',
    assigneeId: 'user-1',
    reporterId: 'user-2',
    sprintId: 'sprint-1',
    labels: ['bug', 'frontend'],
    dueDate: new Date('2025-08-05'),
    estimatedHours: 4,
    loggedHours: 3,
  },
  
  // Задачи для запланированного спринта
  {
    title: 'Создать главный экран приложения',
    description: 'Разработать основной интерфейс с навигацией и основными функциями',
    type: 'story',
    status: 'todo',
    priority: 'high',
    storyPoints: 13,
    position: 5,
    projectId: 'project-1',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    sprintId: 'sprint-2',
    labels: ['ui', 'mobile'],
    dueDate: new Date('2025-08-20'),
    estimatedHours: 24,
    loggedHours: 0,
  },
  {
    title: 'Реализовать список задач',
    description: 'Создать компонент для отображения списка задач с фильтрацией',
    type: 'story',
    status: 'todo',
    priority: 'medium',
    storyPoints: 8,
    position: 6,
    projectId: 'project-1',
    assigneeId: 'user-3',
    reporterId: 'user-1',
    sprintId: 'sprint-2',
    labels: ['ui', 'features'],
    dueDate: new Date('2025-08-25'),
    estimatedHours: 16,
    loggedHours: 0,
  },
  
  // Задачи для завершенного спринта
  {
    title: 'Спроектировать архитектуру базы данных',
    description: 'Создать схему базы данных для хранения проектов, задач и пользователей',
    type: 'story',
    status: 'done',
    priority: 'high',
    storyPoints: 8,
    position: 7,
    projectId: 'project-1',
    assigneeId: 'user-1',
    reporterId: 'user-1',
    sprintId: 'sprint-3',
    labels: ['database', 'architecture'],
    dueDate: new Date('2025-07-10'),
    estimatedHours: 16,
    loggedHours: 16,
  },
  {
    title: 'Настроить CI/CD pipeline',
    description: 'Настроить автоматическую сборку и деплой приложения',
    type: 'story',
    status: 'done',
    priority: 'medium',
    storyPoints: 5,
    position: 8,
    projectId: 'project-1',
    assigneeId: 'user-3',
    reporterId: 'user-1',
    sprintId: 'sprint-3',
    labels: ['devops', 'ci-cd'],
    dueDate: new Date('2025-07-12'),
    estimatedHours: 12,
    loggedHours: 10,
  },
  {
    title: 'Создать документацию API',
    description: 'Написать документацию для REST API с примерами запросов',
    type: 'story',
    status: 'done',
    priority: 'low',
    storyPoints: 3,
    position: 9,
    projectId: 'project-1',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    sprintId: 'sprint-3',
    labels: ['documentation', 'api'],
    dueDate: new Date('2025-07-14'),
    estimatedHours: 8,
    loggedHours: 6,
  },
]; 